// packages/ui/components/Navigation/NavigationItem.tsx
import type { NavigationDrawerItemProps } from "./Navigation.types";

import "./Navigation.module.css";

export function NavigationItem({
  name,
  url,
  icon,
  items,
  type = "nav-header",
  ...props
}: NavigationDrawerItemProps): JSX.Element {
  return (
    <>
      <div className={`nav-item ${type}`}>
        {false && <img src={icon} alt={name} />} {name}
      </div>
      {items &&
        items.map((item, index) => {
          return <NavigationItem {...item} key={index} type="nav-sublink" />;
        })}
    </>
  );
}

export default NavigationItem;

// packages/stencil/src/components/Navigation/NavigationItem.tsx
import { Fragment, FunctionalComponent, h, Host } from '@stencil/core';
import type { NavigationItemProps } from './Navigation.types';

export const NavigationItem: FunctionalComponent<NavigationItemProps> = ({
  name,
  url,
  icon,
  items,
  type = 'nav-header',
  ...props
}) => {
  return (
    <div>
      <div class={`${type} nav-item`} {...props}>
        {icon && <i class={`${icon}`}></i>}
        <h3>{name}</h3>
      </div>
      {items &&
        items.map((item, index) => {
          return <NavigationItem type="nav-sublink" key={index} {...item} />;
        })}
    </div>
  );
};
