// packages/ui/components/Button/Button.tsx
import type { ButtonProps } from './Button.types';

import './Button.css';

export function Button({
  children,
  variant = "primary",
  styles,
  className = "",
  ...props
}: ButtonProps): JSX.Element {

  className += ` btn btn-${variant}`;

  return <button className={className}>{children}</button>;
}

export default Button;

// packages/stencil/src/components/Button/Button.tsx
import { FunctionalComponent, h } from '@stencil/core';
import type { ButtonProps } from './Button.types';

export const Button: FunctionalComponent<ButtonProps> = ({
  variant = 'primary',
  ...props
}) => {
  let { children, className, ...rest } = props;

  if (className) {
    className = `${className} btn-${variant}`;
  } else {
    className = `btn-${variant}`;
  }

  return (
    <button class={className} {...rest}>
      {props.children}
    </button>
  );
};
